---
title: "papilloma"
output: html_document
---

```{r}
pap_counts <- read_delim("papilloma/papilloma_counts.txt", "\t", escape_double = FALSE, trim_ws = TRUE)
pap_counts_1x <- read_delim("papilloma/counts2_papilloma_1x.txt", "\t", escape_double = FALSE, trim_ws = TRUE)
```


```{r}
pap_taxa <- read.csv("papilloma/papilloma_taxa.csv", quote = "", header = TRUE, stringsAsFactors = FALSE, row.names = 1)
pap_taxa <- as.matrix(pap_taxa)
#tax_ann <- subset(tax_ann, select = -c(X))
PAPTAX <- tax_table(pap_taxa)
```

```{r}
pap_counts2 <- pap_counts
#pap_counts_1 <- read_delim("counts2_FINAL_1x.txt", "\t", escape_double = FALSE, trim_ws = TRUE)
#pap_counts_1 <- read_delim("counts2_FINAL_1x.csv", "\t", escape_double = FALSE, trim_ws = TRUE)
#write_csv(pap_counts_1, 'counts2_FINAL_1x.csv')
write_csv(pap_counts2, 'papilloma/PAPcounts.csv')
PAPOTU_counts <- read.csv("papilloma/PAPcounts.csv", quote = "", header = TRUE, stringsAsFactors = FALSE, row.names = 1)
PAPOTU <- otu_table(PAPOTU_counts, taxa_are_rows = TRUE)


pap_counts_1x2 <- pap_counts_1x
write_csv(pap_counts_1x2, 'papilloma/PAPcounts_1x.csv')
PAPOTU_counts_1x <- read.csv("papilloma/PAPcounts_1x.csv", quote = "", header = TRUE, stringsAsFactors = FALSE, row.names = 1)
PAPOTU_1x <- otu_table(PAPOTU_counts_1x, taxa_are_rows = TRUE)

#counts3 <- counts2 %>% mutate_if(is.numeric, ~1 * (. != 0))
#write_csv(counts3, 'VCcounts_test.csv')
```

```{r}
Metadata2 <- read_csv("~/Desktop/Current_work/OTU_Builber/Sequencing_Data_Info_Sheet3.csv")
Metadata3 <- Metadata2
Metadata3$Time <- Metadata3$Time_Collected
Metadata3$Time[which(Metadata3$Time == "T_0")] <- "00_Weeks"
Metadata3$Time[which(Metadata3$Time == "2_week")] <- "02_Weeks"
Metadata3$Time[which(Metadata3$Time == "1_month")] <- "04_Weeks"
Metadata3$Time[which(Metadata3$Time == "3_month")] <- "12_Weeks"
Metadata3$Time[which(Metadata3$Time == "6_month")] <- "24_Weeks"

META <- sample_data(Metadata3)
sample_names(META)= META$SampleID
```

```{r}
PAPPHY <- phyloseq(PAPOTU, PAPTAX, META)
Samples_toRemove <- c("HV_001_27", "HV_002_27", "HV_003_27", "HV_004_27", "HV_005_27", "HV_006_27", "HV_007_27", "HV_008_27",
                      "HV_009_27", "HV_010_27", "HV_011_27", "HV_012_27", "HV_013_27", "HV_014_27", "HV_015_27", "HV_016_27",
                      "HV_017_27", "HV_018_27", "HV_019_27", "HV_020_27", "HV_021_27", "HV_022_27", "HV_023_27", "HV_024_27",
                      "HV_025_27", "HV_026_27", "HV_027_27", "HV_028_27", "HV_029_27", "HV_030_27", "HV_015_20", "HV_015_21", 
                      "HV_020_22", "HV_027_02", "HV_027_03", "HV_027_04", "HV_027_05", "HV_027_06", "HV_027_07", "HV_020_10",
                      "HV_021_13", "HV_027_01","HV_003_15")

PAPPHY2 <- subset_samples(PAPPHY, !(SampleID %in% Samples_toRemove))
```

```{r}
# Extract abundance matrix from the phyloseq object
Total_OTU = as(otu_table(PAPPHY2), "matrix")
# transpose if necessary
Total_OTU <- t(Total_OTU)
# Coerce to data.frame
Total_OTUdf = as.data.frame(Total_OTU)

#merge metadata file with alpha diversity measures:

#Remove samples from metadatafile that were removed from your phyloseq object (ie control samples, repeated samples, and other samples that are of other persons you are not using in this data set (P33, >P43))
Samples_toRemove <- c("HV_001_27", "HV_002_27", "HV_003_27", "HV_004_27", "HV_005_27", "HV_006_27", "HV_007_27", "HV_008_27",
                      "HV_009_27", "HV_010_27", "HV_011_27", "HV_012_27", "HV_013_27", "HV_014_27", "HV_015_27", "HV_016_27",
                      "HV_017_27", "HV_018_27", "HV_019_27", "HV_020_27", "HV_021_27", "HV_022_27", "HV_023_27", "HV_024_27",
                      "HV_025_27", "HV_026_27", "HV_027_27", "HV_028_27", "HV_029_27", "HV_030_27", "HV_015_20", "HV_015_21", 
                      "HV_020_22", "HV_027_02", "HV_027_03", "HV_027_04", "HV_027_05", "HV_027_06", "HV_027_07", "HV_020_10",
                      "HV_021_13", "HV_027_01", "HV_003_15")

Metadata_stat <- Metadata2[!grepl("HV_001_27", Metadata2$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_002_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_027_03", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_027_04", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_027_06", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_027_07", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_021_13", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_027_01", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_020_10", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_015_21", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_027_05", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_020_22", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_027_02", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_015_20", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_003_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_004_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_005_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_006_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_007_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_008_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_009_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_010_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_011_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_012_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_013_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_014_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_015_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_016_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_017_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_018_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_019_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_020_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_021_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_022_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_023_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_024_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_025_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_026_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_027_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_028_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_029_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_030_27", Metadata_stat$SampleID),]
Metadata_stat <- Metadata_stat[!grepl("HV_003_15", Metadata_stat$SampleID),]


#Total_OTUdf2<- Total_OTUdf
#Total_OTUdf2$SampleID <- row.names(Total_OTUdf2)
#Total_OTUdf2 <- subset(Total_OTUdf2, select = c(SampleID))
#Metadata_stat2 <- subset(Metadata_stat, select = c(SampleID))
#anti_join(Metadata_stat2, Total_OTUdf2)

#alpha diversity measures:
Metadata_stat$shannon.vegan <- diversity(Total_OTUdf, index = "shannon")
Metadata_stat$simpson.vegan <- diversity(Total_OTUdf, index = "simpson")
Metadata_stat$invsimpson.vegan <- diversity(Total_OTUdf, index = "invsimpson")
```
```{r}
model_AOV <- aov(shannon.vegan~Gender+Subject/Location+Subject, data = Metadata_stat)
summary(model_AOV)
```
```{r}
PAP_PRUNE<- prune_taxa(taxa_sums(PAPPHY2) > 2, PAPPHY2) 
PAP_PRUNE2 = prune_samples(sample_sums(PAP_PRUNE)>=2, PAP_PRUNE)
```

```{r}
norm_groups <- transform_sample_counts(PAP_PRUNE2, function(x) x / sum(x) )
ord.core_groups.pcoa <- ordinate(norm_groups, method="PCoA", distance="jaccard", na.rm = TRUE)
plot_ordination(norm_groups, ord.core_groups.pcoa, color = "Subject", shape = "Location") +
  geom_point(size=1)
```

```{r}
metadata <- as(sample_data(norm_groups ), "data.frame")
adonis(phyloseq::distance(norm_groups, method="jaccard") ~  Gender+Subject/Location+Subject,
       data = metadata)
```

```{r}
PAPPHY2_LH<- subset_samples(PAPPHY2, Location=="left")
# Extract abundance matrix from the phyloseq object
Total_OTU_LH = as(otu_table(PAPPHY2_LH), "matrix")
# transpose if necessary
Total_OTU_LH <- t(Total_OTU_LH)
# Coerce to data.frame
Total_OTUdf_LH = as.data.frame(Total_OTU_LH)

#merge metadata file with alpha diversity measures:

#Remove samples from metadatafile that were removed from your phyloseq object (ie control samples, repeated samples, and other samples that are of other persons you are not using in this data set (P33, >P43))
Samples_toRemove <- c("HV_001_27", "HV_002_27", "HV_003_27", "HV_004_27", "HV_005_27", "HV_006_27", "HV_007_27", "HV_008_27",
                      "HV_009_27", "HV_010_27", "HV_011_27", "HV_012_27", "HV_013_27", "HV_014_27", "HV_015_27", "HV_016_27",
                      "HV_017_27", "HV_018_27", "HV_019_27", "HV_020_27", "HV_021_27", "HV_022_27", "HV_023_27", "HV_024_27",
                      "HV_025_27", "HV_026_27", "HV_027_27", "HV_028_27", "HV_029_27", "HV_030_27", "HV_015_20", "HV_015_21", 
                      "HV_020_22", "HV_027_02", "HV_027_03", "HV_027_04", "HV_027_05", "HV_027_06", "HV_027_07", "HV_020_10",
                      "HV_021_13", "HV_027_01", "HV_003_15")

Metadata_stat_LH <- Metadata2[!grepl("HV_001_27", Metadata2$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_002_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_027_03", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_027_04", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_027_06", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_027_07", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_021_13", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_027_01", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_020_10", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_015_21", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_027_05", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_020_22", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_027_02", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_015_20", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_003_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_004_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_005_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_006_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_007_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_008_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_009_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_010_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_011_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_012_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_013_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_014_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_015_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_016_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_017_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_018_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_019_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_020_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_021_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_022_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_023_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_024_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_025_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_026_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_027_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_028_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_029_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_030_27", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("HV_003_15", Metadata_stat_LH$SampleID),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("right", Metadata_stat_LH$Location),]
Metadata_stat_LH <- Metadata_stat_LH[!grepl("scalp", Metadata_stat_LH$Location),]


#Total_OTUdf2<- Total_OTUdf
#Total_OTUdf2$SampleID <- row.names(Total_OTUdf2)
#Total_OTUdf2 <- subset(Total_OTUdf2, select = c(SampleID))
#Metadata_stat2 <- subset(Metadata_stat, select = c(SampleID))
#anti_join(Metadata_stat2, Total_OTUdf2)

#alpha diversity measures:
Metadata_stat_LH$shannon.vegan <- diversity(Total_OTUdf_LH, index = "shannon")
Metadata_stat_LH$simpson.vegan <- diversity(Total_OTUdf_LH, index = "simpson")
Metadata_stat_LH$invsimpson.vegan <- diversity(Total_OTUdf_LH, index = "invsimpson")
```
```{r}
model_AOV_LH <- aov(shannon.vegan~Gender+Subject/Time_Collected+Subject, data = Metadata_stat_LH)
summary(model_AOV_LH)
```

```{r}
PAP_PRUNE_LH<- prune_taxa(taxa_sums(PAPPHY2_LH) > 2, PAPPHY2_LH) 
PAP_PRUNE2_LH <- prune_samples(sample_sums(PAP_PRUNE_LH)>=2, PAP_PRUNE_LH)
```
```{r}
norm_groups_LH <- transform_sample_counts(PAP_PRUNE2_LH, function(x) x / sum(x) )
ord.LH.pcoa <- ordinate(norm_groups_LH, method="PCoA", distance="jaccard", na.rm = TRUE)
plot_ordination(norm_groups_LH, ord.LH.pcoa, color = "Subject", shape = "Time_Collected") +
  geom_point(size=1)
```

```{r}
metadata <- as(sample_data(norm_groups_LH), "data.frame")
adonis(phyloseq::distance(norm_groups_LH, method="jaccard") ~  Subject,
       data = metadata)
```
