---
title: "SNP"
output: html_document
---

```{r}
library(vcfR)
library(ape)
```
```{r}
vcf <- read.vcfR("SNP/FINAL_calls.vcf", verbose = FALSE )
dna <- ape::read.dna("SNP/SNPMarkers.fa", format = "fasta")
gff <- read.table("SNP/SNP.gff", sep="\t", quote="")
chrom <- create.chromR(name="Contig_SNP", vcf=vcf, seq=dna, ann=gff, verbose=FALSE)
chrom <- masker(chrom, min_DP = 300, max_DP = 700)
chrom <- proc.chromR(chrom, verbose = FALSE)

```

#CS162761.1
```{r}
vcf <- read.vcfR("SNP/vcf_file/CS162761.1.vcf", verbose = FALSE )
dna <- ape::read.dna("SNP/fasta_markers/CS162761.1.fa", format = "fasta")
gff <- read.table("SNP/GFF/CS162761.1.gff", sep="\t", quote="")
chrom <- create.chromR(name="CS162761.1", vcf=vcf, seq=dna, ann=gff, verbose=FALSE)
plot(chrom)
#chrom <- masker(chrom, min_DP = 300, max_DP = 700)
chrom <- proc.chromR(chrom, verbose = FALSE)
head(chrom)
chromoqc(chrom)
dp <- extract.gt(chrom, element="DP", as.numeric=TRUE)
View(dp)
rownames(dp) <- 1:nrow(dp)
head(dp)
is.na(dp[na.omit(dp == 0)]) <- TRUE
heatmap.bp(dp)
```

#DJ417502.1
```{r}
vcf <- read.vcfR("SNP/vcf_file/fixed/DJ417502.1.vcf", verbose = FALSE )
dna <- ape::read.dna("SNP/fasta_markers/DJ417502.1.fa", format = "fasta")
gff <- read.table("SNP/GFF/DJ417502.1.gff", sep="\t", quote="")
chrom <- create.chromR(name="DJ417502.1", vcf=vcf, seq=dna, ann=gff, verbose=FALSE)
#chrom <- masker(chrom, min_DP = 300, max_DP = 700)
chrom <- proc.chromR(chrom, verbose = FALSE)
head(chrom)
plot(chrom)
chromoqc(chrom)
```
#FB325579.1

#KF022001.1

#KU697902.1

#KU697903.1

#KX077896.1
```{r}
vcf <- read.vcfR("SNP/vcf_file/fixed/KX077896.1.vcf", verbose = FALSE )
dna <- ape::read.dna("SNP/fasta_markers/KX077896.1.fa", format = "fasta")
gff <- read.table("SNP/GFF/KX077896.1.gff", sep="\t", quote="")
chrom <- create.chromR(name="KX077896.1", vcf=vcf, seq=dna, ann=gff, verbose=FALSE)
#chrom <- masker(chrom, min_DP = 300, max_DP = 700)
plot(chrom)
chrom <- proc.chromR(chrom, verbose = FALSE)
chromoqc(chrom)
head(chrom)
chrom2<-masker(chrom,min_QUAL = 1, min_DP = 1, max_DP = 10000, min_MQ = 20, max_MQ = 100, preserve = FALSE)
dp <- extract.gt(chrom2, element="DP", as.numeric=TRUE)
rownames(dp) <- 1:nrow(dp)
head(dp)
is.na(dp[na.omit(dp == 0)]) <- TRUE
heatmap.bp(dp)
```

#MK359990.1
