---
title: "ALPHA_BETA"
output: html_document
---

#OVERALL Diversity
```{r}
# Extract abundance matrix from the phyloseq object
Total_core_OTU = as(otu_table(PHY2), "matrix")
# transpose if necessary
Total_core_OTU <- t(Total_core_OTU)
# Coerce to data.frame
Total_core_OTUdf = as.data.frame(Total_core_OTU)

#merge metadata file with alpha diversity measures:

#Remove samples from metadatafile that were removed from your phyloseq object (ie control samples, repeated samples, and other samples that are of other persons you are not using in this data set (P33, >P43))
Samples_toRemove <- c("HV_001_27", "HV_002_27", "HV_003_27", "HV_004_27", "HV_005_27", "HV_006_27", "HV_007_27", "HV_008_27",
                      "HV_009_27", "HV_010_27", "HV_011_27", "HV_012_27", "HV_013_27", "HV_014_27", "HV_015_27", "HV_016_27",
                      "HV_017_27", "HV_018_27", "HV_019_27", "HV_020_27", "HV_021_27", "HV_022_27", "HV_023_27", "HV_024_27",
                      "HV_025_27", "HV_026_27", "HV_027_27", "HV_028_27", "HV_029_27", "HV_030_27", "HV_015_20", "HV_015_21", 
                      "HV_020_22", "HV_027_02", "HV_027_03", "HV_027_04", "HV_027_05", "HV_027_06", "HV_027_07", "HV_020_10",
                      "HV_021_13", "HV_027_01")

Metadata_all_stat <- Metadata2[!grepl("HV_001_27", Metadata2$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_002_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_027_03", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_027_04", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_027_06", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_027_07", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_021_13", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_027_01", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_020_10", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_015_21", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_027_05", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_020_22", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_027_02", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_015_20", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_003_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_004_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_005_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_006_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_007_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_008_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_009_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_010_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_011_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_012_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_013_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_014_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_015_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_016_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_017_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_018_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_019_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_020_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_021_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_022_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_023_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_024_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_025_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_026_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_027_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_028_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_029_27", Metadata_all_stat$SampleID),]
Metadata_all_stat <- Metadata_all_stat[!grepl("HV_030_27", Metadata_all_stat$SampleID),]

Metadata_all_stat$shannon.vegan <- diversity(Total_core_OTUdf, index = "shannon")
Metadata_all_stat$simpson.vegan <- diversity(Total_core_OTUdf, index = "simpson")
Metadata_all_stat$invsimpson.vegan <- diversity(Total_core_OTUdf, index = "invsimpson")
```
```{r}
model_call_AOV <- aov(shannon.vegan~Gender+Subject/Location+ Subject/Time_Collected+Subject, data = Metadata_all_stat)
summary(model_call_AOV)
```
```{r}
norm_all <- transform_sample_counts(PHY2 , function(x) x / sum(x) )
ord.all <- ordinate(norm_all, method="PCoA", distance="bray")
plot_ordination(norm_all, ord.all, color = "Subject", shape = "Time_Collected") +
  geom_point(size=1)
```
```{r}
metadata_all <- as(sample_data(norm_all ), "data.frame")
adonis(phyloseq::distance(norm_all, method="bray") ~  Gender+Subject/Location+ Subject/Time_Week+Subject,
       data = metadata_all)
```

#CORE Diversity
```{r}
# Extract abundance matrix from the phyloseq object
Total_core_OTU = as(otu_table(CORE), "matrix")
# transpose if necessary
Total_core_OTU <- t(Total_core_OTU)
# Coerce to data.frame
Total_core_OTUdf = as.data.frame(Total_core_OTU)

#merge metadata file with alpha diversity measures:

#Remove samples from metadatafile that were removed from your phyloseq object (ie control samples, repeated samples, and other samples that are of other persons you are not using in this data set (P33, >P43))
Samples_toRemove <- c("HV_001_27", "HV_002_27", "HV_003_27", "HV_004_27", "HV_005_27", "HV_006_27", "HV_007_27", "HV_008_27",
                      "HV_009_27", "HV_010_27", "HV_011_27", "HV_012_27", "HV_013_27", "HV_014_27", "HV_015_27", "HV_016_27",
                      "HV_017_27", "HV_018_27", "HV_019_27", "HV_020_27", "HV_021_27", "HV_022_27", "HV_023_27", "HV_024_27",
                      "HV_025_27", "HV_026_27", "HV_027_27", "HV_028_27", "HV_029_27", "HV_030_27", "HV_015_20", "HV_015_21", 
                      "HV_020_22", "HV_027_02", "HV_027_03", "HV_027_04", "HV_027_05", "HV_027_06", "HV_027_07", "HV_020_10",
                      "HV_021_13", "HV_027_01")

Metadata_core_stat <- Metadata2[!grepl("HV_001_27", Metadata2$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_002_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_027_03", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_027_04", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_027_06", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_027_07", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_021_13", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_027_01", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_020_10", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_015_21", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_027_05", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_020_22", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_027_02", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_015_20", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_003_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_004_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_005_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_006_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_007_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_008_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_009_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_010_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_011_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_012_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_013_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_014_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_015_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_016_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_017_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_018_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_019_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_020_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_021_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_022_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_023_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_024_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_025_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_026_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_027_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_028_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_029_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_030_27", Metadata_core_stat$SampleID),]

Metadata_core_stat$shannon.vegan <- diversity(Total_core_OTUdf, index = "shannon")
Metadata_core_stat$simpson.vegan <- diversity(Total_core_OTUdf, index = "simpson")
Metadata_core_stat$invsimpson.vegan <- diversity(Total_core_OTUdf, index = "invsimpson")
```
```{r}
model_core_AOV <- aov(shannon.vegan~Gender+Subject/Location+ Subject/Time_Week+Subject, data = Metadata_core_stat)
summary(model_core_AOV)
```
```{r}
norm_CORE <- transform_sample_counts(CORE , function(x) x / sum(x) )
ord.CORE <- ordinate(norm_CORE, method="PCoA", distance="bray")
plot_ordination(norm_CORE, ord.CORE, color = "Subject", shape = "Time_Collected") +
  geom_point(size=1)
```
```{r}
metadata_CORE <- as(sample_data(norm_CORE ), "data.frame")
adonis(phyloseq::distance(norm_CORE, method="bray") ~  Gender+Subject/Location+ Subject/Time_Week+Subject,
       data = metadata_CORE)
```

#core merge 
```{r}
# Extract abundance matrix from the phyloseq object
Total_core_OTU = as(otu_table(core_total_merge), "matrix")
# transpose if necessary
Total_core_OTU <- t(Total_core_OTU)
# Coerce to data.frame
Total_core_OTUdf = as.data.frame(Total_core_OTU)

#merge metadata file with alpha diversity measures:

#Remove samples from metadatafile that were removed from your phyloseq object (ie control samples, repeated samples, and other samples that are of other persons you are not using in this data set (P33, >P43))
Samples_toRemove <- c("HV_001_27", "HV_002_27", "HV_003_27", "HV_004_27", "HV_005_27", "HV_006_27", "HV_007_27", "HV_008_27",
                      "HV_009_27", "HV_010_27", "HV_011_27", "HV_012_27", "HV_013_27", "HV_014_27", "HV_015_27", "HV_016_27",
                      "HV_017_27", "HV_018_27", "HV_019_27", "HV_020_27", "HV_021_27", "HV_022_27", "HV_023_27", "HV_024_27",
                      "HV_025_27", "HV_026_27", "HV_027_27", "HV_028_27", "HV_029_27", "HV_030_27", "HV_015_20", "HV_015_21", 
                      "HV_020_22", "HV_027_02", "HV_027_03", "HV_027_04", "HV_027_05", "HV_027_06", "HV_027_07", "HV_020_10",
                      "HV_021_13", "HV_027_01")

Metadata_core_stat <- Metadata2[!grepl("HV_001_27", Metadata2$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_002_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_027_03", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_027_04", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_027_06", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_027_07", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_021_13", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_027_01", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_020_10", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_015_21", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_027_05", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_020_22", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_027_02", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_015_20", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_003_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_004_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_005_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_006_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_007_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_008_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_009_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_010_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_011_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_012_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_013_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_014_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_015_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_016_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_017_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_018_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_019_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_020_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_021_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_022_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_023_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_024_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_025_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_026_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_027_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_028_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_029_27", Metadata_core_stat$SampleID),]
Metadata_core_stat <- Metadata_core_stat[!grepl("HV_030_27", Metadata_core_stat$SampleID),]

#alpha diversity measures:
Metadata_core_stat$shannon.vegan <- diversity(Total_core_OTUdf, index = "shannon")
Metadata_core_stat$simpson.vegan <- diversity(Total_core_OTUdf, index = "simpson")
Metadata_core_stat$invsimpson.vegan <- diversity(Total_core_OTUdf, index = "invsimpson")
```
```{r}
model_core_AOV <- aov(shannon.vegan~Gender+Subject/Location+ Subject/Time_Collected+Subject, data = Metadata_core_stat)
summary(model_core_AOV)
```
```{r}
norm_core_groups <- transform_sample_counts(core_total_merge , function(x) x / sum(x) )
ord.core_groups.pcoa <- ordinate(norm_core_groups, method="PCoA", distance="jaccard")
plot_ordination(norm_core_groups, ord.core_groups.pcoa, color = "Subject", shape = "Time_Collected") +
  geom_point(size=1)
```
```{r}
metadata_core <- as(sample_data(norm_core_groups ), "data.frame")
adonis(phyloseq::distance(norm_core_groups, method="jaccard") ~  Gender+Subject+Subject/Time_Collected,
       data = metadata_core)
```

#LH Core
```{r}
# Extract abundance matrix from the phyloseq object
LH_core_OTU = as(otu_table(core_LH_merge), "matrix")
# transpose if necessary
LH_core_OTU <- t(LH_core_OTU)
# Coerce to data.frame
LH_core_OTUdf = as.data.frame(LH_core_OTU)

#merge metadata file with alpha diversity measures:

#Remove samples from metadatafile that were removed from your phyloseq object (ie control samples, repeated samples, and other samples that are of other persons you are not using in this data set (P33, >P43))
Samples_toRemove <- c("HV_001_27", "HV_002_27", "HV_003_27", "HV_004_27", "HV_005_27", "HV_006_27", "HV_007_27", "HV_008_27",
                      "HV_009_27", "HV_010_27", "HV_011_27", "HV_012_27", "HV_013_27", "HV_014_27", "HV_015_27", "HV_016_27",
                      "HV_017_27", "HV_018_27", "HV_019_27", "HV_020_27", "HV_021_27", "HV_022_27", "HV_023_27", "HV_024_27",
                      "HV_025_27", "HV_026_27", "HV_027_27", "HV_028_27", "HV_029_27", "HV_030_27", "HV_015_20", "HV_015_21", 
                      "HV_020_22", "HV_027_02", "HV_027_03", "HV_027_04", "HV_027_05", "HV_027_06", "HV_027_07", "HV_020_10",
                      "HV_021_13", "HV_027_01")

LH_Metadata_core_stat <- Metadata2[!grepl("HV_001_27", Metadata2$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_002_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_027_03", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_027_04", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_027_06", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_027_07", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_021_13", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_027_01", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_020_10", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_015_21", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_027_05", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_020_22", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_027_02", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_015_20", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_003_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_004_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_005_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_006_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_007_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_008_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_009_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_010_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_011_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_012_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_013_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_014_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_015_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_016_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_017_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_018_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_019_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_020_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_021_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_022_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_023_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_024_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_025_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_026_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_027_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_028_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_029_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("HV_030_27", LH_Metadata_core_stat$SampleID),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("right", LH_Metadata_core_stat$Location),]
LH_Metadata_core_stat <- LH_Metadata_core_stat[!grepl("scalp", LH_Metadata_core_stat$Location),]
#alpha diversity measures:
LH_Metadata_core_stat$shannon.vegan <- diversity(LH_core_OTUdf, index = "shannon")
LH_Metadata_core_stat$simpson.vegan <- diversity(LH_core_OTUdf, index = "simpson")
LH_Metadata_core_stat$invsimpson.vegan <- diversity(LH_core_OTUdf, index = "invsimpson")
```
```{r}
model_LH_AOV <- aov(shannon.vegan~Gender+ Subject/Time_Week+Subject, data = LH_Metadata_core_stat)
summary(model_LH_AOV)
```
```{r}
norm_LH_groups <- transform_sample_counts(core_LH_merge , function(x) x / sum(x) )
ord.LH_groups.pcoa <- ordinate(norm_LH_groups, method="PCoA", distance="bray")
plot_ordination(norm_LH_groups, ord.LH_groups.pcoa, color = "Subject", shape = "Time_Collected") +
  geom_point(size=1)
```
```{r}
metadata_LH_core <- as(sample_data(norm_LH_groups ), "data.frame")
adonis(phyloseq::distance(norm_LH_groups, method="bray") ~  Gender+Subject+Subject/Time_Week,
       data=metadata_LH_core)
```
#RH Core
```{r}
# Extract abundance matrix from the phyloseq object
RH_core_OTU = as(otu_table(core_RH_merge), "matrix")
# transpose if necessary
RH_core_OTU <- t(RH_core_OTU)
# Coerce to data.frame
RH_core_OTUdf = as.data.frame(RH_core_OTU)

#merge metadata file with alpha diversity measures:

#Remove samples from metadatafile that were removed from your phyloseq object (ie control samples, repeated samples, and other samples that are of other persons you are not using in this data set (P33, >P43))
Samples_toRemove <- c("HV_001_27", "HV_002_27", "HV_003_27", "HV_004_27", "HV_005_27", "HV_006_27", "HV_007_27", "HV_008_27",
                      "HV_009_27", "HV_010_27", "HV_011_27", "HV_012_27", "HV_013_27", "HV_014_27", "HV_015_27", "HV_016_27",
                      "HV_017_27", "HV_018_27", "HV_019_27", "HV_020_27", "HV_021_27", "HV_022_27", "HV_023_27", "HV_024_27",
                      "HV_025_27", "HV_026_27", "HV_027_27", "HV_028_27", "HV_029_27", "HV_030_27", "HV_015_20", "HV_015_21", 
                      "HV_020_22", "HV_027_02", "HV_027_03", "HV_027_04", "HV_027_05", "HV_027_06", "HV_027_07", "HV_020_10",
                      "HV_021_13", "HV_027_01")

RH_Metadata_core_stat <- Metadata2[!grepl("HV_001_27", Metadata2$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_002_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_027_03", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_027_04", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_027_06", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_027_07", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_021_13", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_027_01", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_020_10", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_015_21", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_027_05", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_020_22", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_027_02", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_015_20", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_003_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_004_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_005_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_006_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_007_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_008_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_009_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_010_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_011_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_012_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_013_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_014_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_015_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_016_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_017_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_018_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_019_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_020_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_021_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_022_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_023_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_024_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_025_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_026_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_027_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_028_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_029_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("HV_030_27", RH_Metadata_core_stat$SampleID),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("left", RH_Metadata_core_stat$Location),]
RH_Metadata_core_stat <- RH_Metadata_core_stat[!grepl("scalp", RH_Metadata_core_stat$Location),]
#alpha diversity measures:
RH_Metadata_core_stat$shannon.vegan <- diversity(RH_core_OTUdf, index = "shannon")
RH_Metadata_core_stat$simpson.vegan <- diversity(RH_core_OTUdf, index = "simpson")
RH_Metadata_core_stat$invsimpson.vegan <- diversity(RH_core_OTUdf, index = "invsimpson")
```
```{r}
model_RH_AOV <- aov(shannon.vegan~Gender+ Subject/Time_Week+Subject, data = RH_Metadata_core_stat)
summary(model_RH_AOV)
```
```{r}
norm_RH_groups <- transform_sample_counts(core_RH_merge , function(x) x / sum(x) )
ord.RH_groups.pcoa <- ordinate(norm_RH_groups, method="PCoA", distance="bray")
plot_ordination(norm_RH_groups, ord.RH_groups.pcoa, color = "Subject", shape = "Time_Collected") +
  geom_point(size=1)
```
```{r}
metadata_RH_core <- as(sample_data(norm_RH_groups ), "data.frame")
adonis(phyloseq::distance(norm_RH_groups, method="bray") ~  Gender+Subject+Subject/Time_Week,
       data=metadata_RH_core)
```

#SC Core
```{r}
# Extract abundance matrix from the phyloseq object
SC_core_OTU = as(otu_table(core_SC_merge), "matrix")
# transpose if necessary
SC_core_OTU <- t(SC_core_OTU)
# Coerce to data.frame
SC_core_OTUdf = as.data.frame(SC_core_OTU)

#merge metadata file with alpha diversity measures:

#Remove samples from metadatafile that were removed from your phyloseq object (ie control samples, repeated samples, and other samples that are of other persons you are not using in this data set (P33, >P43))
Samples_toRemove <- c("HV_001_27", "HV_002_27", "HV_003_27", "HV_004_27", "HV_005_27", "HV_006_27", "HV_007_27", "HV_008_27",
                      "HV_009_27", "HV_010_27", "HV_011_27", "HV_012_27", "HV_013_27", "HV_014_27", "HV_015_27", "HV_016_27",
                      "HV_017_27", "HV_018_27", "HV_019_27", "HV_020_27", "HV_021_27", "HV_022_27", "HV_023_27", "HV_024_27",
                      "HV_025_27", "HV_026_27", "HV_027_27", "HV_028_27", "HV_029_27", "HV_030_27", "HV_015_20", "HV_015_21", 
                      "HV_020_22", "HV_027_02", "HV_027_03", "HV_027_04", "HV_027_05", "HV_027_06", "HV_027_07", "HV_020_10",
                      "HV_021_13", "HV_027_01")

SC_Metadata_core_stat <- Metadata2[!grepl("HV_001_27", Metadata2$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_002_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_027_03", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_027_04", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_027_06", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_027_07", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_021_13", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_027_01", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_020_10", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_015_21", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_027_05", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_020_22", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_027_02", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_015_20", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_003_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_004_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_005_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_006_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_007_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_008_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_009_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_010_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_011_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_012_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_013_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_014_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_015_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_016_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_017_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_018_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_019_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_020_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_021_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_022_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_023_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_024_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_025_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_026_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_027_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_028_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_029_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("HV_030_27", SC_Metadata_core_stat$SampleID),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("right", SC_Metadata_core_stat$Location),]
SC_Metadata_core_stat <- SC_Metadata_core_stat[!grepl("left", SC_Metadata_core_stat$Location),]
#alpha diversity measures:
SC_Metadata_core_stat$shannon.vegan <- diversity(SC_core_OTUdf, index = "shannon")
SC_Metadata_core_stat$simpson.vegan <- diversity(SC_core_OTUdf, index = "simpson")
SC_Metadata_core_stat$invsimpson.vegan <- diversity(SC_core_OTUdf, index = "invsimpson")
```
```{r}
model_SC_AOV <- aov(shannon.vegan~Gender+ Subject/Time_Week+Subject, data = SC_Metadata_core_stat)
summary(model_SC_AOV)
```
```{r}
norm_SC_groups <- transform_sample_counts(core_SC_merge , function(x) x / sum(x) )
ord.SC_groups.pcoa <- ordinate(norm_SC_groups, method="PCoA", distance="bray")
plot_ordination(norm_SC_groups, ord.SC_groups.pcoa, color = "Subject", shape = "Time_Collected") +
  geom_point(size=1)
```
```{r}
metadata_SC_core <- as(sample_data(norm_SC_groups ), "data.frame")
adonis(phyloseq::distance(norm_SC_groups, method="bray") ~  Gender+Subject+Subject/Time_Week,
       data=metadata_SC_core)
```

#Hands Core
```{r}
LH<- subset_samples(JVIRAL_FINAL, Location=="left")
RH<- subset_samples(JVIRAL_FINAL, Location=="right")
HANDS <- merge_phyloseq(LH,RH)
# Extract abundance matrix from the phyloseq object
hands_core_OTU = as(otu_table(HANDS), "matrix")
# transpose if necessary
hands_core_OTU <- t(hands_core_OTU)
# Coerce to data.frame
hands_core_OTUdf = as.data.frame(hands_core_OTU)

#merge metadata file with alpha diversity measures:

#Remove samples from metadatafile that were removed from your phyloseq object (ie control samples, repeated samples, and other samples that are of other persons you are not using in this data set (P33, >P43))
Samples_toRemove <- c("HV_001_27", "HV_002_27", "HV_003_27", "HV_004_27", "HV_005_27", "HV_006_27", "HV_007_27", "HV_008_27",
                      "HV_009_27", "HV_010_27", "HV_011_27", "HV_012_27", "HV_013_27", "HV_014_27", "HV_015_27", "HV_016_27",
                      "HV_017_27", "HV_018_27", "HV_019_27", "HV_020_27", "HV_021_27", "HV_022_27", "HV_023_27", "HV_024_27",
                      "HV_025_27", "HV_026_27", "HV_027_27", "HV_028_27", "HV_029_27", "HV_030_27", "HV_015_20", "HV_015_21", 
                      "HV_020_22", "HV_027_02", "HV_027_03", "HV_027_04", "HV_027_05", "HV_027_06", "HV_027_07", "HV_020_10",
                      "HV_021_13", "HV_027_01")

hands_Metadata_core_stat <- Metadata2[!grepl("HV_001_27", Metadata2$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_002_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_027_03", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_027_04", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_027_06", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_027_07", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_021_13", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_027_01", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_020_10", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_015_21", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_027_05", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_020_22", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_027_02", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_015_20", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_003_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_004_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_005_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_006_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_007_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_008_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_009_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_010_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_011_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_012_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_013_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_014_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_015_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_016_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_017_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_018_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_019_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_020_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_021_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_022_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_023_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_024_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_025_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_026_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_027_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_028_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_029_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("HV_030_27", hands_Metadata_core_stat$SampleID),]
hands_Metadata_core_stat <- hands_Metadata_core_stat[!grepl("scalp", hands_Metadata_core_stat$Location),]

#alpha diversity measures:
hands_Metadata_core_stat$shannon.vegan <- diversity(hands_core_OTUdf, index = "shannon")
hands_Metadata_core_stat$simpson.vegan <- diversity(hands_core_OTUdf, index = "simpson")
hands_Metadata_core_stat$invsimpson.vegan <- diversity(hands_core_OTUdf, index = "invsimpson")
```
```{r}
model_hands_AOV <- aov(shannon.vegan~Gender+Subject/Location+ Subject/Time_Collected+Subject, data = hands_Metadata_core_stat)
summary(model_hands_AOV)
```
```{r}
norm_hands_groups <- transform_sample_counts(HANDS , function(x) x / sum(x) )
ord.hands_groups.pcoa <- ordinate(norm_hands_groups, method="PCoA", distance="bray")
plot_ordination(norm_hands_groups, ord.hands_groups.pcoa, color = "Subject", shape = "Time_Collected") +
  geom_point(size=1)
```
```{r}
metadata_hands_core <- as(sample_data(norm_hands_groups ), "data.frame")
adonis(phyloseq::distance(norm_hands_groups, method="bray") ~  Gender+Subject+Subject/Time_Collected+Subject/Location,
       data=metadata_hands_core)
```
#Core Remove
```{r}
# Extract abundance matrix from the phyloseq object
core_rm_core_OTU = as(otu_table(core_rm), "matrix")
# transpose if necessary
core_rm_core_OTU <- t(core_rm_core_OTU)
# Coerce to data.frame
core_rm_core_OTUdf = as.data.frame(core_rm_core_OTU)

#merge metadata file with alpha diversity measures:

#Remove samples from metadatafile that were removed from your phyloseq object (ie control samples, repeated samples, and other samples that are of other persons you are not using in this data set (P33, >P43))
Samples_toRemove <- c("HV_001_27", "HV_002_27", "HV_003_27", "HV_004_27", "HV_005_27", "HV_006_27", "HV_007_27", "HV_008_27",
                      "HV_009_27", "HV_010_27", "HV_011_27", "HV_012_27", "HV_013_27", "HV_014_27", "HV_015_27", "HV_016_27",
                      "HV_017_27", "HV_018_27", "HV_019_27", "HV_020_27", "HV_021_27", "HV_022_27", "HV_023_27", "HV_024_27",
                      "HV_025_27", "HV_026_27", "HV_027_27", "HV_028_27", "HV_029_27", "HV_030_27", "HV_015_20", "HV_015_21", 
                      "HV_020_22", "HV_027_02", "HV_027_03", "HV_027_04", "HV_027_05", "HV_027_06", "HV_027_07", "HV_020_10",
                      "HV_021_13", "HV_027_01")

core_rm_Metadata_core_stat <- Metadata2[!grepl("HV_001_27", Metadata2$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_002_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_027_03", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_027_04", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_027_06", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_027_07", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_021_13", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_027_01", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_020_10", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_015_21", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_027_05", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_020_22", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_027_02", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_015_20", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_003_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_004_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_005_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_006_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_007_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_008_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_009_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_010_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_011_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_012_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_013_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_014_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_015_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_016_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_017_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_018_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_019_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_020_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_021_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_022_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_023_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_024_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_025_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_026_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_027_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_028_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_029_27", core_rm_Metadata_core_stat$SampleID),]
core_rm_Metadata_core_stat <- core_rm_Metadata_core_stat[!grepl("HV_030_27", core_rm_Metadata_core_stat$SampleID),]


#alpha diversity measures:
core_rm_Metadata_core_stat$shannon.vegan <- diversity(core_rm_core_OTUdf, index = "shannon")
core_rm_Metadata_core_stat$simpson.vegan <- diversity(core_rm_core_OTUdf, index = "simpson")
core_rm_Metadata_core_stat$invsimpson.vegan <- diversity(core_rm_core_OTUdf, index = "invsimpson")
```
```{r}
model_core_rm_AOV <- aov(shannon.vegan~Gender+ Subject/Time_Week+Subject+Subject/Location, data = core_rm_Metadata_core_stat)
summary(model_core_rm_AOV)
```
```{r}
norm_core_rm_groups <- transform_sample_counts(core_rm , function(x) x / sum(x) )
ord.core_rm_groups.pcoa <- ordinate(norm_core_rm_groups, method="PCoA", distance="bray")
plot_ordination(norm_core_rm_groups, ord.core_rm_groups.pcoa, color = "Subject", shape = "Time_Collected") +
  geom_point(size=1)
```
```{r}
metadata_core_rm_core <- as(sample_data(norm_core_rm_groups ), "data.frame")
adonis(phyloseq::distance(norm_core_rm_groups, method="bray") ~  Gender+Subject+Subject/Time_Week+Subject/Location,
       data=metadata_core_rm_core)
```

#LH Core Remove
```{r}
# Extract abundance matrix from the phyloseq object
LH_rm_core_OTU = as(otu_table(core_LH_rm), "matrix")
# transpose if necessary
LH_rm_core_OTU <- t(LH_rm_core_OTU)
# Coerce to data.frame
LH_rm_core_OTUdf = as.data.frame(LH_rm_core_OTU)

#merge metadata file with alpha diversity measures:

#Remove samples from metadatafile that were removed from your phyloseq object (ie control samples, repeated samples, and other samples that are of other persons you are not using in this data set (P33, >P43))
Samples_toRemove <- c("HV_001_27", "HV_002_27", "HV_003_27", "HV_004_27", "HV_005_27", "HV_006_27", "HV_007_27", "HV_008_27",
                      "HV_009_27", "HV_010_27", "HV_011_27", "HV_012_27", "HV_013_27", "HV_014_27", "HV_015_27", "HV_016_27",
                      "HV_017_27", "HV_018_27", "HV_019_27", "HV_020_27", "HV_021_27", "HV_022_27", "HV_023_27", "HV_024_27",
                      "HV_025_27", "HV_026_27", "HV_027_27", "HV_028_27", "HV_029_27", "HV_030_27", "HV_015_20", "HV_015_21", 
                      "HV_020_22", "HV_027_02", "HV_027_03", "HV_027_04", "HV_027_05", "HV_027_06", "HV_027_07", "HV_020_10",
                      "HV_021_13", "HV_027_01")

LH_rm_Metadata_core_stat <- Metadata2[!grepl("HV_001_27", Metadata2$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_002_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_027_03", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_027_04", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_027_06", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_027_07", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_021_13", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_027_01", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_020_10", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_015_21", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_027_05", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_020_22", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_027_02", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_015_20", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_003_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_004_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_005_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_006_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_007_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_008_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_009_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_010_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_011_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_012_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_013_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_014_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_015_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_016_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_017_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_018_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_019_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_020_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_021_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_022_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_023_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_024_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_025_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_026_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_027_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_028_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_029_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("HV_030_27", LH_rm_Metadata_core_stat$SampleID),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("right", LH_rm_Metadata_core_stat$Location),]
LH_rm_Metadata_core_stat <- LH_rm_Metadata_core_stat[!grepl("scalp", LH_rm_Metadata_core_stat$Location),]
#alpha diversity measures:
LH_rm_Metadata_core_stat$shannon.vegan <- diversity(LH_rm_core_OTUdf, index = "shannon")
LH_rm_Metadata_core_stat$simpson.vegan <- diversity(LH_rm_core_OTUdf, index = "simpson")
LH_rm_Metadata_core_stat$invsimpson.vegan <- diversity(LH_rm_core_OTUdf, index = "invsimpson")
```
```{r}
model_LH_rm_AOV <- aov(shannon.vegan~Gender+ Subject/Time_Week+Subject, data = LH_rm_Metadata_core_stat)
summary(model_LH_rm_AOV)
```
```{r}
norm_LH_rm_groups <- transform_sample_counts(core_LH_rm , function(x) x / sum(x) )
ord.LH_rm_groups.pcoa <- ordinate(norm_LH_rm_groups, method="PCoA", distance="bray")
plot_ordination(norm_LH_rm_groups, ord.LH_rm_groups.pcoa, color = "Subject", shape = "Time_Collected") +
  geom_point(size=1)
```
```{r}
metadata_LH_rm_core <- as(sample_data(norm_LH_rm_groups ), "data.frame")
adonis(phyloseq::distance(norm_LH_rm_groups, method="bray") ~  Gender+Subject+Subject/Time_Week,
       data=metadata_LH_rm_core)
```

#RH Core Remove
```{r}
# Extract abundance matrix from the phyloseq object
RH_rm_core_OTU = as(otu_table(core_RH_rm), "matrix")
# transpose if necessary
RH_rm_core_OTU <- t(RH_rm_core_OTU)
# Coerce to data.frame
RH_rm_core_OTUdf = as.data.frame(RH_rm_core_OTU)

#merge metadata file with alpha diversity measures:

#Remove samples from metadatafile that were removed from your phyloseq object (ie control samples, repeated samples, and other samples that are of other persons you are not using in this data set (P33, >P43))
Samples_toRemove <- c("HV_001_27", "HV_002_27", "HV_003_27", "HV_004_27", "HV_005_27", "HV_006_27", "HV_007_27", "HV_008_27",
                      "HV_009_27", "HV_010_27", "HV_011_27", "HV_012_27", "HV_013_27", "HV_014_27", "HV_015_27", "HV_016_27",
                      "HV_017_27", "HV_018_27", "HV_019_27", "HV_020_27", "HV_021_27", "HV_022_27", "HV_023_27", "HV_024_27",
                      "HV_025_27", "HV_026_27", "HV_027_27", "HV_028_27", "HV_029_27", "HV_030_27", "HV_015_20", "HV_015_21", 
                      "HV_020_22", "HV_027_02", "HV_027_03", "HV_027_04", "HV_027_05", "HV_027_06", "HV_027_07", "HV_020_10",
                      "HV_021_13", "HV_027_01")

RH_rm_Metadata_core_stat <- Metadata2[!grepl("HV_001_27", Metadata2$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_002_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_027_03", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_027_04", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_027_06", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_027_07", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_021_13", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_027_01", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_020_10", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_015_21", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_027_05", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_020_22", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_027_02", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_015_20", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_003_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_004_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_005_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_006_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_007_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_008_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_009_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_010_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_011_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_012_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_013_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_014_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_015_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_016_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_017_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_018_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_019_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_020_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_021_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_022_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_023_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_024_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_025_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_026_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_027_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_028_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_029_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("HV_030_27", RH_rm_Metadata_core_stat$SampleID),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("scalp", RH_rm_Metadata_core_stat$Location),]
RH_rm_Metadata_core_stat <- RH_rm_Metadata_core_stat[!grepl("left", RH_rm_Metadata_core_stat$Location),]
#alpha diversity measures:
RH_rm_Metadata_core_stat$shannon.vegan <- diversity(RH_rm_core_OTUdf, index = "shannon")
RH_rm_Metadata_core_stat$simpson.vegan <- diversity(RH_rm_core_OTUdf, index = "simpson")
RH_rm_Metadata_core_stat$invsimpson.vegan <- diversity(RH_rm_core_OTUdf, index = "invsimpson")
```
```{r}
model_RH_rm_AOV <- aov(shannon.vegan~Gender+ Subject/Time_Week+Subject, data = RH_rm_Metadata_core_stat)
summary(model_RH_rm_AOV)
```
```{r}
norm_RH_rm_groups <- transform_sample_counts(core_RH_rm , function(x) x / sum(x) )
ord.RH_rm_groups.pcoa <- ordinate(norm_RH_rm_groups, method="PCoA", distance="bray")
plot_ordination(norm_RH_rm_groups, ord.RH_rm_groups.pcoa, color = "Subject", shape = "Time_Collected") +
  geom_point(size=1)
```
```{r}
metadata_RH_rm_core <- as(sample_data(norm_RH_rm_groups ), "data.frame")
adonis(phyloseq::distance(norm_RH_rm_groups, method="bray") ~  Gender+Subject+Subject/Time_Week,
       data=metadata_RH_rm_core)
```
#SC Core Remove
```{r}
# Extract abundance matrix from the phyloseq object
SC_rm_core_OTU = as(otu_table(core_SC_rm), "matrix")
# transpose if necessary
SC_rm_core_OTU <- t(SC_rm_core_OTU)
# Coerce to data.frame
SC_rm_core_OTUdf = as.data.frame(SC_rm_core_OTU)

#merge metadata file with alpha diversity measures:

#Remove samples from metadatafile that were removed from your phyloseq object (ie control samples, repeated samples, and other samples that are of other persons you are not using in this data set (P33, >P43))
Samples_toRemove <- c("HV_001_27", "HV_002_27", "HV_003_27", "HV_004_27", "HV_005_27", "HV_006_27", "HV_007_27", "HV_008_27",
                      "HV_009_27", "HV_010_27", "HV_011_27", "HV_012_27", "HV_013_27", "HV_014_27", "HV_015_27", "HV_016_27",
                      "HV_017_27", "HV_018_27", "HV_019_27", "HV_020_27", "HV_021_27", "HV_022_27", "HV_023_27", "HV_024_27",
                      "HV_025_27", "HV_026_27", "HV_027_27", "HV_028_27", "HV_029_27", "HV_030_27", "HV_015_20", "HV_015_21", 
                      "HV_020_22", "HV_027_02", "HV_027_03", "HV_027_04", "HV_027_05", "HV_027_06", "HV_027_07", "HV_020_10",
                      "HV_021_13", "HV_027_01")

SC_rm_Metadata_core_stat <- Metadata2[!grepl("HV_001_27", Metadata2$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_002_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_027_03", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_027_04", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_027_06", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_027_07", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_021_13", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_027_01", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_020_10", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_015_21", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_027_05", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_020_22", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_027_02", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_015_20", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_003_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_004_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_005_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_006_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_007_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_008_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_009_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_010_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_011_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_012_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_013_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_014_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_015_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_016_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_017_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_018_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_019_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_020_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_021_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_022_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_023_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_024_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_025_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_026_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_027_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_028_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_029_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("HV_030_27", SC_rm_Metadata_core_stat$SampleID),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("right", SC_rm_Metadata_core_stat$Location),]
SC_rm_Metadata_core_stat <- SC_rm_Metadata_core_stat[!grepl("left", SC_rm_Metadata_core_stat$Location),]
#alpha diversity measures:
SC_rm_Metadata_core_stat$shannon.vegan <- diversity(SC_rm_core_OTUdf, index = "shannon")
SC_rm_Metadata_core_stat$simpson.vegan <- diversity(SC_rm_core_OTUdf, index = "simpson")
SC_rm_Metadata_core_stat$invsimpson.vegan <- diversity(SC_rm_core_OTUdf, index = "invsimpson")
```
```{r}
model_SC_rm_AOV <- aov(shannon.vegan~Gender+ Subject/Time_Week+Subject, data = SC_rm_Metadata_core_stat)
summary(model_SC_rm_AOV)
```
```{r}
norm_SC_rm_groups <- transform_sample_counts(core_SC_rm , function(x) x / sum(x) )
ord.SC_rm_groups.pcoa <- ordinate(norm_SC_rm_groups, method="PCoA", distance="bray")
plot_ordination(norm_SC_rm_groups, ord.SC_rm_groups.pcoa, color = "Subject", shape = "Time_Collected") +
  geom_point(size=1)
```
```{r}
metadata_SC_rm_core <- as(sample_data(norm_SC_rm_groups ), "data.frame")
adonis(phyloseq::distance(norm_SC_rm_groups, method="bray") ~  Gender+Subject+Subject/Time_Week,
       data=metadata_SC_rm_core)
```

#Hands Core Remove 
```{r}
# Extract abundance matrix from the phyloseq object
hands_rm_core_OTU = as(otu_table(core_HANDS_rm), "matrix")
# transpose if necessary
hands_rm_core_OTU <- t(hands_rm_core_OTU)
# Coerce to data.frame
hands_rm_core_OTUdf = as.data.frame(hands_rm_core_OTU)

#merge metadata file with alpha diversity measures:

#Remove samples from metadatafile that were removed from your phyloseq object (ie control samples, repeated samples, and other samples that are of other persons you are not using in this data set (P33, >P43))
Samples_toRemove <- c("HV_001_27", "HV_002_27", "HV_003_27", "HV_004_27", "HV_005_27", "HV_006_27", "HV_007_27", "HV_008_27",
                      "HV_009_27", "HV_010_27", "HV_011_27", "HV_012_27", "HV_013_27", "HV_014_27", "HV_015_27", "HV_016_27",
                      "HV_017_27", "HV_018_27", "HV_019_27", "HV_020_27", "HV_021_27", "HV_022_27", "HV_023_27", "HV_024_27",
                      "HV_025_27", "HV_026_27", "HV_027_27", "HV_028_27", "HV_029_27", "HV_030_27", "HV_015_20", "HV_015_21", 
                      "HV_020_22", "HV_027_02", "HV_027_03", "HV_027_04", "HV_027_05", "HV_027_06", "HV_027_07", "HV_020_10",
                      "HV_021_13", "HV_027_01")

hands_rm_Metadata_core_stat <- Metadata2[!grepl("HV_001_27", Metadata2$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_002_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_027_03", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_027_04", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_027_06", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_027_07", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_021_13", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_027_01", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_020_10", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_015_21", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_027_05", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_020_22", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_027_02", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_015_20", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_003_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_004_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_005_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_006_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_007_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_008_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_009_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_010_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_011_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_012_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_013_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_014_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_015_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_016_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_017_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_018_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_019_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_020_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_021_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_022_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_023_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_024_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_025_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_026_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_027_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_028_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_029_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("HV_030_27", hands_rm_Metadata_core_stat$SampleID),]
hands_rm_Metadata_core_stat <- hands_rm_Metadata_core_stat[!grepl("scalp", hands_rm_Metadata_core_stat$Location),]

#alpha diversity measures:
hands_rm_Metadata_core_stat$shannon.vegan <- diversity(hands_rm_core_OTUdf, index = "shannon")
hands_rm_Metadata_core_stat$simpson.vegan <- diversity(hands_rm_core_OTUdf, index = "simpson")
hands_rm_Metadata_core_stat$invsimpson.vegan <- diversity(hands_rm_core_OTUdf, index = "invsimpson")
```
```{r}
model_hands_rm_AOV <- aov(shannon.vegan~Gender+ Subject/Time_Week+Subject, data = hands_rm_Metadata_core_stat)
summary(model_hands_rm_AOV)
```
```{r}
norm_hands_rm_groups <- transform_sample_counts(core_HANDS_rm , function(x) x / sum(x) )
ord.hands_rm_groups.pcoa <- ordinate(norm_hands_rm_groups, method="PCoA", distance="bray")
plot_ordination(norm_hands_rm_groups, ord.hands_rm_groups.pcoa, color = "Subject", shape = "Time_Collected") +
  geom_point(size=1)
```
```{r}
metadata_hands_rm_core <- as(sample_data(norm_hands_rm_groups ), "data.frame")
adonis(phyloseq::distance(norm_hands_rm_groups, method="bray") ~  Gender+Subject+Subject/Time_Week,
       data=metadata_hands_rm_core)
```

#DESEQ from Core

#P1-15 Core

core_P1_20_merge <- merge_phyloseq(core_P01, core_P02, core_P03, core_P04, core_P05, core_P06, core_P07, 
                            core_P08, core_P09, core_P10, core_P11, core_P12, core_P13, core_P14,
                            core_P15, core_P16, core_P17, core_P18, core_P19, core_P20)
                            
```{r}
# Extract abundance matrix from the phyloseq object
Total_core_01_20_OTU = as(otu_table(core_P1_20_merge), "matrix")
# transpose if necessary
Total_core_01_20_OTU <- t(Total_core_01_20_OTU)
# Coerce to data.frame
Total_core_01_20_OTUdf = as.data.frame(Total_core_01_20_OTU)

#merge metadata file with alpha diversity measures:

#Remove samples from metadatafile that were removed from your phyloseq object (ie control samples, repeated samples, and other samples that are of other persons you are not using in this data set (P33, >P43))
Samples_toRemove <- c("HV_001_27", "HV_002_27", "HV_003_27", "HV_004_27", "HV_005_27", "HV_006_27", "HV_007_27", "HV_008_27",
                      "HV_009_27", "HV_010_27", "HV_011_27", "HV_012_27", "HV_013_27", "HV_014_27", "HV_015_27", "HV_016_27",
                      "HV_017_27", "HV_018_27", "HV_019_27", "HV_020_27", "HV_021_27", "HV_022_27", "HV_023_27", "HV_024_27",
                      "HV_025_27", "HV_026_27", "HV_027_27", "HV_028_27", "HV_029_27", "HV_030_27", "HV_015_20", "HV_015_21", 
                      "HV_020_22", "HV_027_02", "HV_027_03", "HV_027_04", "HV_027_05", "HV_027_06", "HV_027_07", "HV_020_10",
                      "HV_021_13", "HV_027_01")

Metadata_core_01_20_stat <- Metadata2[!grepl("HV_001_27", Metadata2$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_002_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_027_03", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_027_04", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_027_06", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_027_07", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_021_13", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_027_01", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_020_10", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_015_21", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_027_05", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_020_22", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_027_02", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_015_20", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_003_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_004_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_005_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_006_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_007_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_008_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_009_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_010_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_011_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_012_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_013_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_014_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_015_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_016_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_017_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_018_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_019_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_020_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_021_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_022_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_023_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_024_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_025_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_026_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_027_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_028_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_029_27", Metadata_core_01_20_stat$SampleID),]
Metadata_core_01_20_stat <- Metadata_core_01_20_stat[!grepl("HV_030_27", Metadata_core_01_20_stat$SampleID),]

#alpha diversity measures:
Metadata_core_01_20_stat$shannon.vegan <- diversity(Total_core_01_20_OTUdf, index = "shannon")
Metadata_core_01_20_stat$simpson.vegan <- diversity(Total_core_01_20_OTUdf, index = "simpson")
Metadata_core_01_20_stat$invsimpson.vegan <- diversity(Total_core_01_20_OTUdf, index = "invsimpson")
```
```{r}
model_core_01_20_AOV <- aov(shannon.vegan~Gender+ Subject/Time_Week+Subject, data = Metadata_core_01_20_stat)
summary(model_core_01_20_AOV)
```
```{r}
norm_core_01_20_groups <- transform_sample_counts(core_01_20_merge , function(x) x / sum(x) )
ord.core_01_20_groups.pcoa <- ordinate(norm_core_01_20_groups, method="PCoA", distance="bray")
plot_ordination(norm_RH_groups, ord.core_01_20_groups.pcoa, color = "Subject", shape = "Time_Collected") +
  geom_point(size=1)
```
```{r}
metadata_core_01_20 <- as(sample_data(norm_core_01_20_groups ), "data.frame")
adonis(phyloseq::distance(norm_core_01_20_groups, method="bray") ~  Gender+Subject+Subject/Time_Week,
```                            